// <auto-generated />
using System;
using KlinikVeriSiniflandirmaSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlinikVeriSiniflandirmaSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515172555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlinikVeriSiniflandirmaSistemi.Models.ClinicalClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClinicalClasses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "success",
                            Description = "Değerler normal aralıktadır.",
                            Name = "Normal",
                            RiskLevel = "Düşük Risk"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "warning",
                            Description = "Bir veya daha fazla klinik değer risk sınırındadır.",
                            Name = "Riskli",
                            RiskLevel = "Orta Risk"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "danger",
                            Description = "Acil değerlendirme gerektiren klinik bulgular vardır.",
                            Name = "Acil",
                            RiskLevel = "Yüksek Risk"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "orange",
                            Description = "Kronik hastalık veya düzenli takip gereksinimi vardır.",
                            Name = "Kronik Takip Gerekli",
                            RiskLevel = "Orta-Yüksek Risk"
                        });
                });

            modelBuilder.Entity("KlinikVeriSiniflandirmaSistemi.Models.ClinicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodSugar")
                        .HasColumnType("integer");

                    b.Property<decimal>("BodyTemperature")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<int>("Cholesterol")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicalClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DiastolicBloodPressure")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Pulse")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("SystolicBloodPressure")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalClassId");

                    b.HasIndex("PatientId");

                    b.ToTable("ClinicalRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodSugar = 95,
                            BodyTemperature = 36.6m,
                            Cholesterol = 180,
                            ClinicalClassId = 1,
                            Complaint = "Rutin kontrol",
                            Diagnosis = "Genel durum iyi",
                            DiastolicBloodPressure = 76,
                            Notes = "Kontrol önerildi.",
                            PatientId = 1,
                            Pulse = 72,
                            RecordDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicBloodPressure = 118
                        },
                        new
                        {
                            Id = 2,
                            BloodSugar = 160,
                            BodyTemperature = 36.9m,
                            Cholesterol = 230,
                            ClinicalClassId = 2,
                            Complaint = "Baş ağrısı ve halsizlik",
                            Diagnosis = "Hipertansiyon şüpheli",
                            DiastolicBloodPressure = 96,
                            Notes = "Tansiyon takibi önerildi.",
                            PatientId = 2,
                            Pulse = 88,
                            RecordDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicBloodPressure = 152
                        },
                        new
                        {
                            Id = 3,
                            BloodSugar = 190,
                            BodyTemperature = 36.8m,
                            Cholesterol = 245,
                            ClinicalClassId = 4,
                            Complaint = "Şeker takibi",
                            Diagnosis = "Kronik diyabet",
                            DiastolicBloodPressure = 85,
                            Notes = "Kronik takip gerekli.",
                            PatientId = 3,
                            Pulse = 82,
                            RecordDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicBloodPressure = 135
                        });
                });

            modelBuilder.Entity("KlinikVeriSiniflandirmaSistemi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PatientNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PatientNumber")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ankara",
                            BirthDate = new DateTime(1990, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ayşe",
                            Gender = "Kadın",
                            LastName = "Yılmaz",
                            PatientNumber = "10000000001",
                            Phone = "05551234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "İstanbul",
                            BirthDate = new DateTime(1978, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mehmet",
                            Gender = "Erkek",
                            LastName = "Demir",
                            PatientNumber = "10000000002",
                            Phone = "05557654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "İzmir",
                            BirthDate = new DateTime(1965, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 8, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elif",
                            Gender = "Kadın",
                            LastName = "Kaya",
                            PatientNumber = "10000000003",
                            Phone = "05559876543"
                        });
                });

            modelBuilder.Entity("KlinikVeriSiniflandirmaSistemi.Models.ClinicalRecord", b =>
                {
                    b.HasOne("KlinikVeriSiniflandirmaSistemi.Models.ClinicalClass", "ClinicalClass")
                        .WithMany("ClinicalRecords")
                        .HasForeignKey("ClinicalClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlinikVeriSiniflandirmaSistemi.Models.Patient", "Patient")
                        .WithMany("ClinicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicalClass");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KlinikVeriSiniflandirmaSistemi.Models.ClinicalClass", b =>
                {
                    b.Navigation("ClinicalRecords");
                });

            modelBuilder.Entity("KlinikVeriSiniflandirmaSistemi.Models.Patient", b =>
                {
                    b.Navigation("ClinicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
