// <auto-generated />
using System;
using KeyloggerTespitSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeyloggerTespitSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessReportId")
                        .HasColumnType("integer");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessReportId")
                        .IsUnique();

                    b.ToTable("AnalysisResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProcessReportId = 1,
                            RiskLevel = "High",
                            Summary = "Seed kayıt yüksek riskli örnek olarak eklenmiştir.",
                            TotalScore = 100
                        });
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.DetectionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("RiskPoint")
                        .HasColumnType("integer");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DetectionRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yayıncı bilgisi boş veya bilinmeyen olarak girilmiş processleri işaretler.",
                            IsActive = true,
                            Name = "Bilinmeyen Yayıncı",
                            RiskPoint = 15,
                            RuleType = "UnknownPublisher"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sistem açılışında otomatik çalıştığı bildirilen processleri işaretler.",
                            IsActive = true,
                            Name = "Başlangıçta Çalışma",
                            RiskPoint = 15,
                            RuleType = "RunsAtStartup"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Temp veya AppData klasöründen çalıştığı bildirilen processleri işaretler.",
                            IsActive = true,
                            Name = "Temp/AppData Konumu",
                            RiskPoint = 20,
                            RuleType = "RunsFromTempOrAppData"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Klavye erişimi şüphesi manuel olarak bildirilen kayıtları işaretler.",
                            IsActive = true,
                            Name = "Klavye Erişimi Şüphesi",
                            RiskPoint = 25,
                            RuleType = "KeyboardAccessSuspicion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ağ bağlantısı bulunduğu bildirilen processleri ek risk olarak değerlendirir.",
                            IsActive = true,
                            Name = "Şüpheli Ağ Bağlantısı",
                            RiskPoint = 15,
                            RuleType = "SuspiciousNetworkConnection"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sistem dosyası gibi göründüğü manuel bildirilen adları işaretler.",
                            IsActive = true,
                            Name = "Sahte Sistem Dosyası Adı",
                            RiskPoint = 20,
                            RuleType = "FakeSystemFileName"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Arka planda çalıştığı bildirilen processleri düşük ek riskle değerlendirir.",
                            IsActive = true,
                            Name = "Arka Planda Çalışma",
                            RiskPoint = 10,
                            RuleType = "RunsInBackground"
                        });
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.ProcessReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("FakeSystemFileName")
                        .HasColumnType("boolean");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HasNetworkConnection")
                        .HasColumnType("boolean");

                    b.Property<bool>("KeyboardAccessSuspicion")
                        .HasColumnType("boolean");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("RunsAtStartup")
                        .HasColumnType("boolean");

                    b.Property<bool>("RunsFromTempOrAppData")
                        .HasColumnType("boolean");

                    b.Property<bool>("RunsInBackground")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProcessReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Savunma amaçlı örnek şüpheli kayıt.",
                            FakeSystemFileName = true,
                            FilePath = "C:\\Users\\Student\\AppData\\Roaming\\svhost.exe",
                            HasNetworkConnection = true,
                            KeyboardAccessSuspicion = true,
                            ProcessName = "svhost.exe",
                            Publisher = "Unknown",
                            RunsAtStartup = true,
                            RunsFromTempOrAppData = true,
                            RunsInBackground = true,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Recommendations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Process bilgilerini kayıt altında tutun ve yayıncı/dosya yolu değişirse yeniden analiz edin.",
                            IsActive = true,
                            RiskLevel = "Low",
                            Title = "Düşük risk takibi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dosya konumu, yayıncı bilgisi ve başlangıç ayarlarını kontrol edin. Gerekirse güvenlik ekibi veya öğretmenle paylaşın.",
                            IsActive = true,
                            RiskLevel = "Medium",
                            Title = "Manuel inceleme önerilir"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bu kayıt yüksek riskli görünmektedir. Canlı sistemde çalıştırmadan izole laboratuvar ortamında savunma amaçlı inceleyin.",
                            IsActive = true,
                            RiskLevel = "High",
                            Title = "İzolasyon ve ayrıntılı analiz"
                        });
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sistem yöneticisi",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Analiz yapan öğrenci kullanıcı",
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.TriggeredRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedScore")
                        .HasColumnType("integer");

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("integer");

                    b.Property<int>("DetectionRuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.HasIndex("DetectionRuleId");

                    b.ToTable("TriggeredRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedScore = 15,
                            AnalysisResultId = 1,
                            DetectionRuleId = 1,
                            Reason = "Yayıncı bilgisi bilinmeyen olarak değerlendirildi."
                        },
                        new
                        {
                            Id = 2,
                            AddedScore = 15,
                            AnalysisResultId = 1,
                            DetectionRuleId = 2,
                            Reason = "Başlangıçta otomatik çalıştığı bildirildi."
                        },
                        new
                        {
                            Id = 3,
                            AddedScore = 20,
                            AnalysisResultId = 1,
                            DetectionRuleId = 3,
                            Reason = "Temp veya AppData konumundan çalıştığı bildirildi."
                        },
                        new
                        {
                            Id = 4,
                            AddedScore = 25,
                            AnalysisResultId = 1,
                            DetectionRuleId = 4,
                            Reason = "Klavye erişimi şüphesi manuel olarak işaretlendi."
                        },
                        new
                        {
                            Id = 5,
                            AddedScore = 15,
                            AnalysisResultId = 1,
                            DetectionRuleId = 5,
                            Reason = "Ağ bağlantısı bulunduğu bildirildi."
                        },
                        new
                        {
                            Id = 6,
                            AddedScore = 20,
                            AnalysisResultId = 1,
                            DetectionRuleId = 6,
                            Reason = "Sahte sistem dosyası adı şüphesi işaretlendi."
                        },
                        new
                        {
                            Id = 7,
                            AddedScore = 10,
                            AnalysisResultId = 1,
                            DetectionRuleId = 7,
                            Reason = "Arka planda çalışma davranışı bildirildi."
                        });
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@local.test",
                            FullName = "Admin Kullanıcı",
                            IsActive = true,
                            PasswordHash = "86FFC443B908A9836418317AF641C17317C03AA9A9F0FC42C614E70DCE5EFFA8",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.AnalysisResult", b =>
                {
                    b.HasOne("KeyloggerTespitSistemi.Models.ProcessReport", "ProcessReport")
                        .WithOne("AnalysisResult")
                        .HasForeignKey("KeyloggerTespitSistemi.Models.AnalysisResult", "ProcessReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessReport");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.AuditLog", b =>
                {
                    b.HasOne("KeyloggerTespitSistemi.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.ProcessReport", b =>
                {
                    b.HasOne("KeyloggerTespitSistemi.Models.User", "User")
                        .WithMany("ProcessReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.TriggeredRule", b =>
                {
                    b.HasOne("KeyloggerTespitSistemi.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("TriggeredRules")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyloggerTespitSistemi.Models.DetectionRule", "DetectionRule")
                        .WithMany("TriggeredRules")
                        .HasForeignKey("DetectionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");

                    b.Navigation("DetectionRule");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.User", b =>
                {
                    b.HasOne("KeyloggerTespitSistemi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.AnalysisResult", b =>
                {
                    b.Navigation("TriggeredRules");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.DetectionRule", b =>
                {
                    b.Navigation("TriggeredRules");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.ProcessReport", b =>
                {
                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KeyloggerTespitSistemi.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ProcessReports");
                });
#pragma warning restore 612, 618
        }
    }
}
