services:
  postgres:
    image: postgres:16-alpine
    container_name: klinik-veri-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: klinik_veri_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - klinik_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d klinik_veri_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  klinik_postgres_data:
